name: Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node 18.13.0
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.13.0"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
